const INCORRECT_DATA = 400;
const NOT_FOUND = 404;
const DEFAULT_ERROR = 500;
const DUPLICATE_ERROR_CODE = 409;
const WRONG_EMAIL_OR_PASSWORD = 403;

module.exports = {
  INCORRECT_DATA, NOT_FOUND, DEFAULT_ERROR, DUPLICATE_ERROR_CODE, WRONG_EMAIL_OR_PASSWORD,
};
